name: cloud resume deployment 

on: 
  push:
    branches:
      - main:
      - '/index.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Copy source code to container
      uses: lauchacarro/Azure-Storage-Action@master
      with: 
        enabled-static-website: 'true'
        folder: 'main/'
        index-document: 'index.html'
        error-document: '' # For Angular apps with routing enabled, this must point to the index.html file because the requested routes don't exist phyiscally and blob storage would throw a 404.
        connection-string: ${{ secrets.CONNECTION_STRING }}

